const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');
const { marked } = require('marked');
const puppeteer = require('puppeteer');

/**
 * Converts Markdown content to various formats.
 */
const exportToFormat = async (content, format) => {
  switch (format.toLowerCase()) {
    case 'html':
      return marked(content);
    
    case 'docx':
      return generateDocx(content);
    
    case 'pdf':
      return generatePdf(content);

    case 'json':
      return JSON.stringify({ content, generatedAt: new Date() }, null, 2);

    case 'txt':
    case 'text':
      return content.replace(/[#*`]/g, ''); // Simple markdown strip

    case 'markdown':
    case 'md':
      return content;

    default:
      return content;
  }
};

/**
 * Generates a PDF buffer from markdown content using Puppeteer.
 */
const generatePdf = async (markdown) => {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; line-height: 1.6; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #333; padding-bottom: 10px; }
        h2 { color: #2c3e50; margin-top: 30px; }
        ul { padding-left: 20px; }
        li { margin-bottom: 8px; }
        .footer { margin-top: 50px; font-size: 12px; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
      </style>
    </head>
    <body>
      ${marked(markdown)}
      <div class="footer">Generated by JobBot Career Assistant</div>
    </body>
    </html>
  `;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: "new",
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
    });
    return pdf;
  } finally {
    if (browser) await browser.close();
  }
};

/**
 * Generates a DOCX buffer from markdown content.
 */
const generateDocx = async (markdown) => {
  const lines = markdown.split('\n');
  const children = [];

  lines.forEach(line => {
    if (line.startsWith('# ')) {
      children.push(new Paragraph({ text: line.substring(2), heading: HeadingLevel.HEADING_1 }));
    } else if (line.startsWith('## ')) {
      children.push(new Paragraph({ text: line.substring(3), heading: HeadingLevel.HEADING_2 }));
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      children.push(new Paragraph({ text: line.substring(2), bullet: { level: 0 } }));
    } else if (line.trim() !== '') {
      children.push(new Paragraph({
        children: [new TextRun(line)],
      }));
    }
  });

  const doc = new Document({
    sections: [{
      properties: {},
      children: children,
    }],
  });

  return await Packer.toBuffer(doc);
};

module.exports = { exportToFormat };
